[package]
name = "cairo_runner"
version = "0.1.0"
edition = "2021"

[dependencies]
cairo-vm-base.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
blake2b_simd.workspace = true
#stwo_prover.workspace = true